# Generated by Django 2.1.1 on 2018-12-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signature', '0002_remove_usermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('photo', models.ImageField(upload_to='images/')),
                ('userId', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
